#!/bin/bash

command=$1

case $command in
	test)
		# All unit tests
		for test in t/unit/*.rakutest; do raku -Ilib "$test"; done

		# All integration tests
		for test in t/integration/*.rakutest; do raku -Ilib "$test"; done

		# All example tests
		for test in t/examples/*.rakutest; do raku -Ilib "$test"; done
		;;
	check)
#		echo "=== Run tests ==="
#		./project test
		echo "=== Check for broken rakudoc ==="
		fgrep -Rl '#|' lib
		echo "=== Check for TODOs ==="
		ack TODO lib
		;;
	*)
		echo "Error: Unknown command '$command'" >&2
		exit 1
esac
